In [1]:
# Machine Learning Week 2 Practical Exercises
# Author: Jordan Ung <jordanu107@gmail.com>
# Last Updated: 4/3/19

# Homogenous multidimensional array - less flexible than a list or tuple
# but faster in mathematical computations - ref to. numpy object
import numpy as np
import matplotlib as mpl
import sklearn
import math

# arrays created using arange method - similar to range for lists
####a = np.arange(5) - > array([0, 1, 2, 3, 4])
####b = np.array([1, 3, -2, 0, 0])
####a + b -> array([1, 4, 0, 3, 4])

In [2]:
# Function to calculate Euclidean Distance between two arrays (2b)
# In built way to find Euclidean Distance is np.linalg.norm(a, b)
def my_euclidean_dist(a, b):
    if len(a) != len(b):
        raise ValueError('The dimensions of a and b are not the same.')
    else:
        sum = 0
    for i in range(len(a)):
        sum += pow((a[i] - b[i]), 2)
    return pow(sum, 1.0 / len(a))

In [3]:
# Function to calculate Hamming Distance between two arrays (2c)
def hamming_dist(a, b):
    if len(a) != len(b):
        raise ValueError('The dimensions of a and b are not the same.')
    else:
        sum = 0
    for i in range(len(a)):
        str1 = str(a[i])
        str2 = str(b[i])
        for j in range(len(str1)):
            if str1[j] != str2[j]:
                sum += 1
    return sum

# a = [0, "cat", 800, "??"]
# b = [1, "dog", -266, "??"]
#
# print(hamming_dist(a, b))

In [4]:
# Function to find the dot product between two vectors (3a)
def dot_product(a, b):
    product = 0
    for i in range(len(a)):
        product += a[i] * b[i]
    return product

# print(dot_product([1,2], [1,1]))

3


In [21]:
# A function that calculates the cosine of the angle between two vectors (3b)
def calculate_cos_angle(a, b):
    numerator = dot_product(a, b)
    denominator = my_euclidean_dist(a, [0] * len(a)) * my_euclidean_dist(b, [0] * len(b))
    angle = math.acos(numerator / denominator) # Returns in radians
    return angle * 180 / math.pi

# print(calculate_cos_angle(([1,2]), ([1,1])))

18.434948822922017


In [25]:
m = np.matrix([[1, 2, 3], [4, 2, 1], [6, 2, 0]])
n = np.matrix([[0, 3, 1], [1, 1, 4], [2, 0, 3]])

# print(m + n) 
# print(m - n)

[[ 1 -1  2]
 [ 3  1 -3]
 [ 4  2 -3]]


In [28]:
# (4b)
# print(m*n) same as print(np.dot(m, n)) and vice versa n*m and np.dot(n, m)
# print(m*m) same as print(np.dot(m, m))


[[27 12  5]
 [18 14 14]
 [14 16 20]]
[[27 12  5]
 [18 14 14]
 [14 16 20]]
